{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pro-services.fullname" . }}-pdb
  labels:
    {{- include "pro-services.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "pro-services.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
